name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a Long-Term Support version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          # We don't need the other secrets for the tests to pass

      - name: Trigger Render Deploy
        # Only run this step if the tests pass and it's the main branch
        if: success()
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}